### ISSUE TITLE
Bug in fsolve

### ISSUE THREAD

**Issue by Bogidon** [AllenDowney/ModSimPy#15]
The documentation for modsim.py's `fsolve` says that `x0` can be a scalar or array, matching [scipy's api](https://github.com/scipy/scipy/blob/11509c4a98edded6c59423ac44ca1b7f28fba1fd/scipy/optimize/minpack.py#L61-L62) (well, its defecto one – in the docs it only mentions arrays) . However the sanity check passing `x0` into `func` at the modsim level assumes a scalar type, making arrays not usable.

https://github.com/AllenDowney/ModSimPy/blob/8054670dc6da21708d07dbc459bbfa2149160519/code/modsim.py#L336-L367

## Expected behavior
```python
def func(x):
    return (x-1) * (x-2) * (x-3)

fsolve(func, x0=[0,5])
# -> array([ 1.,  3.])

scipy.optimize.fsolve(func, x0=(0,5))
# -> array([ 1.,  3.])
```

## Actual behavior
```python
def func(x):
    return (x-1) * (x-2) * (x-3)

fsolve(func, x0=[0,5])
# -> TypeError: unsupported operand type(s) for -: 'list' and 'int'

scipy.optimize.fsolve(func, x0=(0,5))
# -> array([ 1.,  3.])
```

**Comment by AllenDowney** [comment]
This should work now.  Please let me know if that's not true.
