### ISSUE TITLE
Vector weirdness

### ISSUE THREAD

**Issue by Bogidon** [AllenDowney/ModSimPy#17]
Haven't dived too deeply into this, but I'm getting the feeling it isn't the intended behavior. There's a lot of weirdness that happens when multiplying a Pint `Quantity` by a modsim `Vector(Quantity)`.

For example, this produces the expected result:
![11-29-2017-03 55 13](https://user-images.githubusercontent.com/3252307/33366405-337a2736-d4b9-11e7-8711-f035d4d1e920.jpg)

however accessing x or y produces an error:
```python
distance_vector.x
# -> Neither Quantity object nor its magnitude ([ 0.5547002   0.83205029]) has attribute 'x'
```

here's a workaround:
```python
acc = 1 * UNITS.m/UNITS.second**2 
acc = (acc.m * Vector(2,3).hat()) * acc.units
acc.x
# -> 0.5547001962252291 meter/second**2 :)
```
---

Unrelated, there's a weird edge case that brakes Pint's TeX formatting: 
![11-29-2017-03 57 09](https://user-images.githubusercontent.com/3252307/33366492-662be1ec-d4b9-11e7-868b-eff2e3319528.jpg)

Looks like there's some kind of superscript formatting going on in the TeX source? Might be a bug on Pint's end.

**Comment by AllenDowney** [comment]
Thanks for letting me know (and sorry I didn't notice this issue sooner!).
This one is hard to fix.  I will have to think about it...

**Comment by AllenDowney** [comment]
Yeah, this is really hard to fix.  I've explained it better in the book and the documentation.  That might be the best I can do.
