### ISSUE TITLE
Syntax error uploading Chapter 5 of ModSimPy

### ISSUE THREAD

**Issue by WhitneyTabor** [AllenDowney/ModSimPy#19]
I was able to upload the Jupyter notebooks for chapters 1-4 of ModSimPy but attempting Chapter 5 (chap05.ipynb) led to the following error:

error was: SyntaxError: JSON Parse error: Unrecognized token '<'

**Comment by AllenDowney** [comment]
Sorry about that, and sorry for the slow reply.  I would guess this issue has been resolved.  Please let me know if it is still a problem.
