### ISSUE TITLE
No Module

### ISSUE THREAD

**Issue by omchabra** [AllenDowney/ModSimPy#20]
Hi, I have been trying to use your repository, however whenever I try to use `from modsim import *` it returns  `ModuleNotFoundError: No module named 'modsim'` How would I go about fixing that?

**Comment by cchocomint** [comment]
same problem here

**Comment by ciaranraymer** [comment]
I'm experiencing the same problem

**Comment by ciaranraymer** [comment]
![image](https://user-images.githubusercontent.com/36703679/36503709-50a04d0e-174e-11e8-87d6-d645212e92ab.png)

**Comment by AllenDowney** [comment]
Sorry about these problems.  The modsim library is a work in progress and not ready to be installed as a package.  In order for Python to find `modsim.py`, it has to be on your Python search path.

I think a good way to work is to start Git Bash, navigate into the ModSimPy folder, and launch Jupyter from there.  I have improved the instructions in the Preface.  Please take a look and see if that helps.

**Comment by Dissandou91000** [comment]
I can't run jupyter notebook from git bash or command prompt. It is only working through anaconda

**Comment by nirathak** [comment]
I've been having the same issue. 

I get this same error (no module named modsim) when I run jupyter in pycharm. Also, I am unable to run jupyter from git bash when I enter "jupyter notebook".  I get an error saying, "jupyter: command not found". However, if I type "ls" I can see that all the files are there. What should I do?

Is it okay to use pycharm, or do I need to switch to anaconda?

**Comment by NckCffn** [comment]
I had the same issues going on:

 1) launch Jupyter notebook from windows and navigate to the modsim/code folder (all good)
 2) from a notebook, try "from modsim import *" command (ImportError      Traceback (most recent call last)
 
I checkout the last line and see an error with matplotlib . After a quick google search, it looks like there was a problem with the 3.0.0 matpltlib release (see referenced stackoverflow link). So I updated matplotlib from Anaconda Navigator and everything so far checks out.

https://stackoverflow.com/questions/52979322/matplotlib-3-0-0-cannot-import-name-get-backend-from-matplotlib

**Comment by rachie1998** [comment]
I am getting an error that there is no module called pint. Does anyone have any ideas on how to fix this?

**Comment by NellaYenwod** [comment]
I can't solve all the installation problems, but I can help with Pint:
```
conda install -c unidata pint
```
You can probably also
```
pip install pint
```
but I haven't tested that.

**Comment by rachie1998** [comment]
Thank you very much, had missed that bit of the instructions!

**Comment by AllenDowney** [comment]
I have now made the ModSim library into a proper Python library on PyPI.  You should be able to install it by running

```
pip install modsim
```
And that should solve these import errors.
