### ISSUE TITLE
plot_state() function seems to be used before being defined

### ISSUE THREAD

**Issue by gabrielgrant** [AllenDowney/ModSimPy#22]
this looks to be the first usage: https://github.com/AllenDowney/ModSimPy/blob/62c3973270a9f7c9507aeb9de9b141cd37b454ad/book/book.tex#L1066 but the first definition i see isn't until section 2.2: https://github.com/AllenDowney/ModSimPy/blob/62c3973270a9f7c9507aeb9de9b141cd37b454ad/book/book.tex#L1220

Looks like the definition should probably be here: https://github.com/AllenDowney/ModSimPy/blob/62c3973270a9f7c9507aeb9de9b141cd37b454ad/book/book.tex#L945

**Comment by AllenDowney** [comment]
Fixed.  Thank you!
