### ISSUE TITLE
salmon.ipynb missing from repo

### ISSUE THREAD

**Issue by Simon-HL** [AllenDowney/ModSimPy#25]
From textbook: Chapter 9 - Case Study - Predicting salmon populations - page 84

> 1. In the repository for this book, you’ll find a notebook called salmon.ipynb,
which contains some data and code to get you started. Read through
the notebook and run it.

There is no notebook named salmon.ipynb. 
salmon_soln is found in the solution folder, but having to filter out exercise-text from the solution is not ideal

**Comment by AllenDowney** [comment]
Fixed.  Thanks for letting me know.

**Comment by AllenDowney** [comment]
Sorry for the slow reply -- it seems I was not "watching" my own repo, for some reason, so I didn't get a notification when you posted the issue.
