### ISSUE TITLE
Define generalizing a function in Chapter 2 notebook

### ISSUE THREAD

**Issue by erhardt** [AllenDowney/ModSimPy#29]
In the "Parameters" section where you already have a "%TODO: expand this transition" you use the phrase "it would be better to generalize this function" so it takes the probabilities p1 and p2 as parameters:" and you haven't used this language before in the notebooks or textbook. In the relevant part of the textbook you do say, " The advantage of using parameters is that you can call the same function many times, providing different arguments each time." Perhaps you can explicitly describe this as generalization there and it will make more sense in the notebook.

**Comment by AllenDowney** [comment]
Good idea.  Done.
