### ISSUE TITLE
The answers to the exercises in each chapter

### ISSUE THREAD

**Issue by sambinliu** [AllenDowney/ModSimPy#31]
I want to know where I can find the answers to the exercises in each chapter.
Thank you！

**Comment by AllenDowney** [comment]
There's a solutions folder in the repo:

https://github.com/AllenDowney/ModSimPy/tree/master/code/soln

**Comment by sambinliu** [comment]
I found that. Thank you:)

**Comment by mehnazara** [comment]
Hello Sir! Have you removed the solutions folder? I cannot find it. Never mind, found it!

**Comment by AllenDowney** [comment]
Yes, when I reorganized the book, I moved the solutions to a private repo. But you can download the zip file from https://drive.google.com/file/d/1TX_jF4904JUbVo-CWt563B7xyHHOfRsP/view?usp=sharing

**Comment by mehnazara** [comment]
Thank you so much, Sir!
