### ISSUE TITLE
scipy solve_ivp not importing with scipy 0.19.1

### ISSUE THREAD

**Issue by gschivley** [AllenDowney/ModSimPy#32]
I ran across the following error(s) when trying to run notebook code on binderhub.

Running the first cell in the `chap02.ipynb` notebook results in an error when modsim attempts to import `solve_ivp` from scipy. It appears that `solve_ivp` [wasn't introduced until after scipy 0.19.1](https://stackoverflow.com/questions/50288685/importerror-cannot-import-name-solve-ivp). 

Unrelated, but the `ast_node_interactivity` value is also throwing an error (shown in screenshot below).

![image](https://user-images.githubusercontent.com/10373332/44374567-e0601400-a4bc-11e8-8719-0a78bcbd10b4.png)

**Comment by AllenDowney** [comment]
I just added an environment.yml file: https://github.com/AllenDowney/ModSimPy/commit/f8528275ee08b92b906841923a785cf615c6c5d7

That should solve this problem, but let me know if not.
