### ISSUE TITLE
Queue case study: can you make a range of UNITS.minutes or any dimensional unit?

### ISSUE THREAD

**Issue by dalton** [AllenDowney/ModSimPy#33]
The [queue case study](https://github.com/AllenDowney/ModSimPy/blob/master/code/queue.ipynb) has instructions to `Set duration, which is the number of time steps to simulate, to 10 hours, expressed in minutes.`

I did this in the following way

```
minutes = UNITS.minutes
hours = UNITS.hour
duration=(10*hours).to(minutes)

```

Later on, there is a prewritten function that uses the system duration to create a range

`for t in linrange(0, system.duration):`

When that runs, it gives me the following error:

>  ---------------------------------------------------------------------------
> DimensionalityError                       Traceback (most recent call last)
> <ipython-input-18-9a5879937b78> in <module>()
>       1 # Solution goes here
> ----> 2 results = run_simulation(system, update)
>       3 plot(results)
> 
> <ipython-input-17-fb71dd244d01> in run_simulation(system, update_func)
>       9     results[0] = x
>      10 
> ---> 11     for t in linrange(0, system.duration):
>      12         x = update_func(x, t, system)
>      13         results[t+1] = x
> 
> ~/projects/modsim.py in linrange(start, stop, step, **options)
>     178         n += 1
>     179 
> --> 180     array = np.linspace(start, stop, int(n), **options)
>     181     if units:
>     182         array = array * units
> 
> ~/miniconda2/envs/simulation/lib/python3.7/site-packages/pint/quantity.py in __int__(self)
>     439         if self.dimensionless:
>     440             return int(self._convert_magnitude_not_inplace(UnitsContainer()))
> --> 441         raise DimensionalityError(self._units, 'dimensionless')
>     442 
>     443     def __long__(self):
> 
> DimensionalityError: Cannot convert from 'minute' to 'dimensionless'
> 

Should `duration` not be using units, is there a way do create a range with units, or am I missing something simple?

**Comment by AllenDowney** [comment]
Excellent question.  In the short term, you can work around this by making `duration` dimensionless.

But I will investigate this and see if there is a good way to make it work the way you wanted it to.

**Comment by dalton** [comment]
Great, thanks! I thought the instructions were leading us to use Pint when they suggested converting 10 hours to minutes, rather than just saying 600 minutes.

I used `for t in linrange(0, system.duration.magnitude):` to convert minutes to a type (float) that worked with linrange.

**Comment by AllenDowney** [comment]
I agree that the instructions were not clear.

I have also updated linspace and linrange to work better with units, so you could try that again.
