### ISSUE TITLE
For Loop Chap02 - TimeSeries Section.

### ISSUE THREAD

**Issue by joenmaca** [AllenDowney/ModSimPy#34]
Hi Allen, 

Something is wrong with the "results" after change the range in a for loop from a number to a minor number, for example I run this:

In [47]:
for i in range(10):
    step(0.3, 0.2)
    results[i] = bikeshare.olin

Displays:

values
--
0 | 5
1 | 5
2 | 4
3 | 4
4 | 5
5 | 5
6 | 5
7 | 4
8 | 3
9 | 2

But when I changed to this:

In [47]:
for i in range(6):
    step(0.3, 0.2)
    results[i] = bikeshare.olin

Displays:

values
--
0 | 2
1 | 1
2 | 1
3 | 0
4 | -1
5 | -1
6 | 5
7 | 4
8 | 3
9 | 2

I dont understand why the values are indexed to 10 positions after run the code with a range of 6 positions.

Thanks in advanced!

**Comment by AllenDowney** [comment]
The second loop is modifying the results from the first loop.

**Comment by joenmaca** [comment]
Yes, when I run the second loop the values in the first 6 positions are changed because of its range, but why the second results stills showing 10 positions? Don't should be only six?

**Comment by AllenDowney** [comment]
The first loop adds 10 elements.  The second loop changes 6 of them.   It
doesn't delete remove any of them.  So there are still 10.

**Comment by joenmaca** [comment]
I got it. Thanks for your answer and for your nice book. It is great for people like me, who is starting with Python.

**Comment by AllenDowney** [comment]
You are welcome.
