### ISSUE TITLE
Line 926 Chap04Soln 

### ISSUE THREAD

**Issue by joenmaca** [AllenDowney/ModSimPy#37]
Hola Profesor Allen, 

In this line it should be 
for p2 in **p2_array**: 
instead of 
for p2 in p1_array: 

Have a good day.

**Comment by AllenDowney** [comment]
I'll fix that as soon as I can.  Thank you!


On Thu, Oct 25, 2018, at 4:16 PM, joenmaca wrote:
> Hola Profesor Allen,


> In this line it should be
>  for p2 in *p2_array*:
>  instead of
>  for p2 in p1_array:


> Have a good day.


> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].

Links:

  1. https://github.com/AllenDowney/ModSimPy/issues/37

**Comment by AllenDowney** [comment]
Fixed.  Thank you!


On Thu, Oct 25, 2018, at 5:11 PM, Allen Downey wrote:
> I'll fix that as soon as I can.  Thank you!
> 
> 
> On Thu, Oct 25, 2018, at 4:16 PM, joenmaca wrote:
>> Hola Profesor Allen,


>> 


>> In this line it should be
>> for p2 in *p2_array*:
>> instead of
>> for p2 in p1_array:
>> 


>> Have a good day.


>> — You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub[1], or mute the
>> thread[2].> 


Links:

  1. https://github.com/AllenDowney/ModSimPy/issues/37
