### ISSUE TITLE
update_func() with UNITS (Pint) an Frame

### ISSUE THREAD

**Issue by jaromrax** [AllenDowney/ModSimPy#38]
When `update_func()` is set to return `State` with `UNITS`,  `run_simulation()` crashes when tryin to enter the `update_func()` output into ModSimDataFrame().

A simple example : pressure increases with depth $dp = \rho dy g$, I initialize params with 
`( p = 0 * Pa, dy =0.1 * m , rho = 1000*kg/m**3)` etc .....

I *(think I)* cannot use `ode_solver` since it is linked with time. So I constrct `update_func()` that retuns `State(p=p,y=y)`, In `run_simulation()` I create `frame=ModSimDataFrame()`, use dimensionless

 ```
ts = linrange( 0,100,0.1)
for t in ts:
```

and when I try to 

`update frame[ t + dy ] = update_func(...)`

it crashes. All is ok, wen I completely remove UNITS. Pitty, isnt it?

**Comment by AllenDowney** [comment]
Yeah, storing a Quantity as an element in a DataFrame is problematic.
I integrated Pint as best I could, but there are still rough edges.
What I recommend to students is exactly what you have done: try to get
it working with units, but if it's more trouble than it's worth, drop
the units.
Good luck!


On Wed, Jan 9, 2019, at 8:36 AM, jaromrax wrote:
> When update_func() is set to return State with UNITS, run_simulation()
> crashes when tryin to enter the update_func() output into
> ModSimDataFrame().> A simple example : pressure increases with depth $dp = \rho dy g$, I
> initialize params with> ( p = 0 * Pa, dy =0.1 * m , rho = 1000*kg/m**3) etc .....


> I *(think I)* cannot use ode_solver since it is linked with time. So I
> constrct update_func() that retuns State(p=p,y=y), In run_simulation()
> I create frame=ModSimDataFrame(), use dimensionless


> ts = linrange( 0,100,0.1) for t in ts:
>> and when I try to


> update frame[ t + dy ] = update_func(...)


> it crashes. All is ok, wen I completely remove UNITS. Pitty, isnt it?> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].

Links:

  1. https://github.com/AllenDowney/ModSimPy/issues/38

**Comment by AllenDowney** [comment]
In Version 3, I replaced the ODE solver with a simple implementation that handles units better.  If you are still interested, you could try this example again and see how it goes.
