### ISSUE TITLE
Issue: Multiple assignment of State in code

### ISSUE THREAD

**Issue by BhagchandLomore11** [AllenDowney/ModSimPy#39]
Hi, 
Could anyone help me?
I am try to execute examples from chapter 18. I am facing this issue with multiple assignment G, X = state
in slope_func. where G and X assigned randomly to values inside state but not on position basis. which is creating further problem. 
I tried to assign G = state.G and X = state.X but that cause problem while running run_ode_solver and shows AttributeError: 'numpy.ndarray' object has no attribute 'G'

**Comment by AllenDowney** [comment]
This might be an issue with versions of Python prior to Python 3.6, which do not guarantee the order of elements in a dictionary.  If you are not on Python >=3.6, you might have to upgrade.
