### ISSUE TITLE
Installing Pint with Python 3.7

### ISSUE THREAD

**Issue by sdziallas** [AllenDowney/ModSimPy#40]
The pint version (0.7.2) in the unidata channel is for Python 3.6. When installing it on the latest version of Anaconda with Python 3.7, this downgrades a large number of packages to Python 3.6. The conda-forge channel has the latest version of pint (0.9) for Python 3.7 and is referenced on the pint website. Unless the older version of pint is required, could you use the conda-forge channel instead?

**Comment by AllenDowney** [comment]
Thanks, Sebastian.  How's this?  5ec16a5

**Comment by sdziallas** [comment]
That seems fine! There's also a reference to unidata in the book itself.

https://github.com/AllenDowney/ModSimPy/blob/a959ae6a67950a35bb8778a3b556d842f0b3036c/book/book.tex#L433

Sorry for not actually providing a pull request - and hoping all is well!

**Comment by AllenDowney** [comment]
Fixed.  Will be in the next release.  Thanks again!
