### ISSUE TITLE
Can't pip install modsimpy - Error Message

### ISSUE THREAD

**Issue by bradynichols** [AllenDowney/ModSimPy#53]
Hey,

I'm trying to begin this book and when following the requirements it says to do `pip install modsimpy`. When I try to do so, it gives me a really long error message:
```
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Brady\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Brady\\AppData\\Local\\Temp\\pip-install-426xujgr\\modsimpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\Brady\\AppData\\Local\\Temp\\pip-install-426xujgr\\modsimpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\Brady\AppData\Local\Temp\pip-install-426xujgr\modsimpy\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Brady\AppData\Local\Temp\pip-install-426xujgr\modsimpy\setup.py", line 20, in <module>
        long_description=readme(),
      File "C:\Users\Brady\AppData\Local\Temp\pip-install-426xujgr\modsimpy\setup.py", line 6, in readme
        return f.read()
      File "C:\Users\Brady\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4990: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I have verified that I can install other packages with pip and I tried reinstalling pip using conda as well as restarting my computer.

How can I fix this? Or is there an alternate way of installing modsimpy now? Thanks!

**Comment by AllenDowney** [comment]
Confirmed.  The problem is that there are Unicode characters in README.rst.  I am fixing it now...

**Comment by bradynichols** [comment]
Update: I was able to pip install modsimpy by enabling the beta UTF-8 encoding option in Windows 10 as noted [here](https://superuser.com/questions/1033088/is-it-possible-to-set-locale-of-a-windows-application-to-utf-8).

Thank you! I'll leave this open in case you do fix the original issue.

**Comment by AllenDowney** [comment]
Good to know.

I just push an update to PyPI. I think it will resolve the issue, but if you are able to test it, please let me know.

Thanks!
