### ISSUE TITLE
Open in Colab links

### ISSUE THREAD

**Issue by fredthedead** [AllenDowney/ModSimPy#57]
Love the content, thanks for making it publicly available!

The _"Click here to run this chapter on Colab"_ links in the notebooks are point to https://colab.research.google.com/github/AllenDowney/ModSimPy/blob/master//chapters/chap12.ipynb (for example in chapter 12 & 13, didn't check the others) - shouldn't they be linking to https://colab.research.google.com/github/AllenDowney/ModSimPy/blob/master/colab/chap12.ipynb instead?

**Comment by AllenDowney** [comment]
The links are as intended for now.  The notebooks in /colab are Version 3.  The ones in /chapters are Version 4.

The organization of the repo is a bit of a mess at the moment.  I'll clean it up gradually.
