### ISSUE TITLE
Installing pint with Python 3.8

### ISSUE THREAD

**Issue by takmark** [AllenDowney/ModSimPy#59]
Downloaded current version (as of April 2021) Anaconda Python 3.8
UnsatisfiableError when trying conda install -c unidata pint as in book Release 4:

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pint -> python[version='2.7.*|3.4.*|3.5.*|3.6.*']

Your python: python=3.8

Thanks for looking into it.

**Comment by moorepants** [comment]
Installing from the `unidata` channel may cause incompatilities. I recommend installing without that channel:

```
conda install pint
```

Or using the `conda-forge` channel as it offers the widest set of compatible packages.

```
conda install -c conda-forge pint
```

**Comment by AllenDowney** [comment]
Thanks, @moorepants
