### ISSUE TITLE
chapter 2 'plot' is not defined

### ISSUE THREAD

**Issue by Truth1984** [AllenDowney/ModSimPy#61]
`plot(results, label='Olin')`

should be 

`plt.plot(results, label='Olin')`

**Comment by AllenDowney** [comment]
What file is this in?

**Comment by Truth1984** [comment]
using [modsim.py]( https://github.com/AllenDowney/ModSimPy/blob/master/modsim.py) with
[chapter2](https://github.com/AllenDowney/ModSimPy/blob/master/chapters/chap02.ipynb)
`# Plotting`

also other chapters have the same problem, like
[chapter3](https://github.com/AllenDowney/ModSimPy/blob/master/chapters/chap03.ipynb)
 
maybe should export `plot=plt.plot` ?

**Comment by AllenDowney** [comment]
Sorry, I let the chapters get out of sync with the code. This should be working now.
Thanks for letting me know!
