### ISSUE TITLE
Pandas dataframe doesn't display on website

### ISSUE THREAD

**Issue by moorepants** [AllenDowney/ModSimPy#62]
![image](https://user-images.githubusercontent.com/276007/125581044-ca92a1e8-1b30-48e0-88ac-cf683d52b5f4.png)

https://allendowney.github.io/ModSimPy/chap17.html#data

`data.head()`

**Comment by moorepants** [comment]
Actually, no results seem to display on that page.

**Comment by AllenDowney** [comment]
Fixed. Thank you!
