### ISSUE TITLE
Ch 01 velocity magnitude

### ISSUE THREAD

**Issue by rodigu** [AllenDowney/ModSimPy#66]
In [chapter 01](https://github.com/AllenDowney/ModSimPy/blob/master/chapters/chap01.ipynb), `In [57]`:
```py
assert abs(v.magnitude - 86.41527642726142) < 1e7
```

Shouldn't this be:
```py
assert abs(v.magnitude - 86.41527642726142) < 1e-7
```

**Comment by AllenDowney** [comment]
Yes. Thanks for letting me know!
