### ISSUE TITLE
Deprecated use of `pd.Series.iteritems`

### ISSUE THREAD

**Issue by rodigu** [AllenDowney/ModSimPy#67]
FutureWarning message:
```
/content/modsim.py:621: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for label, value in res.iteritems():
```

`pd.Series.iteritems` has been deprecated since [pandas 1.5.0](https://pandas.pydata.org/pandas-docs/version/1.5/reference/api/pandas.Series.iteritems.html).

`pd.Series.items` is the recommended alternative: https://pandas.pydata.org/pandas-docs/version/1.5/reference/api/pandas.Series.items.html#pandas.Series.items

**Comment by AllenDowney** [comment]
This should be resolved now. Thank you!
