### ISSUE TITLE
Issue with Pint - Chapter 1

### ISSUE THREAD

**Issue by iacisme** [AllenDowney/ModSimPy#69]
Hi;

I'm going through your book and I'm doing the `Computation with units` example.

When I run the following line:
```
t = math.sqrt(2 * h / a)
```

I get the following error:

![image](https://user-images.githubusercontent.com/72644814/235042100-292a6d93-68f2-4aa1-9639-2fe4b2186037.png)

I'm note sure how to trouble-shoot it. 

Am I doing something wrong, or is there an issue with `pint`?

Thanks!

**Comment by AllenDowney** [comment]
Are you reporting an error or asking for help debugging?

It looks like the notebook is working: https://colab.research.google.com/github/AllenDowney/ModSimPy/blob/master/chapters/chap01.ipynb

If you have been experimenting in the notebook (which is good), you might have changed the value of `h` or `a` so they no longer have compatible units.

**Comment by iacisme** [comment]
I thought I was reporting an error. 

The other day I tried your notebooks. It threw the same error on colab as the screen shot above. It's the reason I posted something because it didn't seem to work.

I just tried your colab notebook and it's working now, so I'll figure out what's going on.

Thanks.

**Comment by AllenDowney** [comment]
OK, not sure what happened there. Maybe you executed the cells out of order, so the variables did not have the intended values?

But let me know if you're able to track it down -- maybe there's something I should warn people about.
