### ISSUE TITLE
Mythbusters Falling Penny Myth Link is Broken

### ISSUE THREAD

**Issue by vikashsahu** [AllenDowney/ModSimPy#90]
The outgoing link in [this section](https://allendowney.github.io/ModSimPy/chap01.html#the-falling-penny-myth) for the Mythbusters testing the falling penny case study is broken. I'm not sure if you want to remove it entirely, or perhaps link to a YouTube video that illustrates their experiment.

![image](https://github.com/user-attachments/assets/0731fea7-a6cc-4c25-96d1-94dc9c8e863f)

**Comment by vikashsahu** [comment]
Text to grep for:
> The television show Mythbusters has tested the myth

**Comment by AllenDowney** [comment]
I changed the link so it forwards here: https://www.youtube.com/watch?v=16Ci_2bN_zc
